# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0.xci
# IP: The module: 'mipsfpga_test2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipsfpga_test2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0.xci
# IP: The module: 'mipsfpga_test2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mipsfpga_test2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
