# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/MIPSfpga_Peripheral_2017/MIPSfpga_axi4.xdc

# Block Designs: bd/MIPSfpga_system/MIPSfpga_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system || ORIG_REF_NAME==MIPSfpga_system}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0/MIPSfpga_system_MIPS_MicroAptiv_UP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_MIPS_MicroAptiv_UP_0_0 || ORIG_REF_NAME==MIPSfpga_system_MIPS_MicroAptiv_UP_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0/MIPSfpga_system_ahblite_axi_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_ahblite_axi_bridge_0_0 || ORIG_REF_NAME==MIPSfpga_system_ahblite_axi_bridge_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_0_0/MIPSfpga_system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_0_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_interconnect_0_0/MIPSfpga_system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_interconnect_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_interconnect_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/MIPSfpga_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xbar_0 || ORIG_REF_NAME==MIPSfpga_system_xbar_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/MIPSfpga_system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_bram_ctrl_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/MIPSfpga_system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_blk_mem_gen_0_0 || ORIG_REF_NAME==MIPSfpga_system_blk_mem_gen_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_ds_buf_0_0/MIPSfpga_system_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_ds_buf_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_ds_buf_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_1_0/MIPSfpga_system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_1_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_1_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_2_0/MIPSfpga_system_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_2_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_2_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_0_0/MIPSfpga_system_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_vector_logic_0_0 || ORIG_REF_NAME==MIPSfpga_system_util_vector_logic_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_util_vector_logic_1_0/MIPSfpga_system_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_util_vector_logic_1_0 || ORIG_REF_NAME==MIPSfpga_system_util_vector_logic_1_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconstant_3_0/MIPSfpga_system_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconstant_3_0 || ORIG_REF_NAME==MIPSfpga_system_xlconstant_3_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_1_0/MIPSfpga_system_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_bram_ctrl_1_0 || ORIG_REF_NAME==MIPSfpga_system_axi_bram_ctrl_1_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_blk_mem_gen_1_0 || ORIG_REF_NAME==MIPSfpga_system_blk_mem_gen_1_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_PWM_w_Int_0_0/MIPSfpga_system_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_PWM_w_Int_0_0 || ORIG_REF_NAME==MIPSfpga_system_PWM_w_Int_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_xlconcat_0_0/MIPSfpga_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_xlconcat_0_0 || ORIG_REF_NAME==MIPSfpga_system_xlconcat_0_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/MIPSfpga_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_0 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_0}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/MIPSfpga_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_1 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_1}]

# IP: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/MIPSfpga_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIPSfpga_system_auto_pc_2 || ORIG_REF_NAME==MIPSfpga_system_auto_pc_2}]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0/MIPSfpga_system_ahblite_axi_bridge_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/MIPSfpga_system_xbar_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_gpio_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/MIPSfpga_system_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/MIPSfpga_system_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_clk_wiz_0_0 || ORIG_REF_NAME==MIPSfpga_system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MIPSfpga_system_axi_uart16550_0_0 || ORIG_REF_NAME==MIPSfpga_system_axi_uart16550_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_1_0/MIPSfpga_system_axi_bram_ctrl_1_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_1_0/MIPSfpga_system_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/MIPSfpga_system_auto_pc_0_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/MIPSfpga_system_auto_pc_1_ooc.xdc

# XDC: bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/MIPSfpga_system_auto_pc_2_ooc.xdc

# XDC: bd/MIPSfpga_system/MIPSfpga_system_ooc.xdc
