# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/git/Nexys4DDR_Master.xdc

# Block Designs: bd/mipsfpga_test2/mipsfpga_test2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2 || ORIG_REF_NAME==mipsfpga_test2}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_MIPS_MicroAptiv_UP_0_0/mipsfpga_test2_MIPS_MicroAptiv_UP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_MIPS_MicroAptiv_UP_0_0 || ORIG_REF_NAME==mipsfpga_test2_MIPS_MicroAptiv_UP_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_ahblite_axi_bridge_0_0/mipsfpga_test2_ahblite_axi_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_ahblite_axi_bridge_0_0 || ORIG_REF_NAME==mipsfpga_test2_ahblite_axi_bridge_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_axi_interconnect_0_0/mipsfpga_test2_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_axi_interconnect_0_0 || ORIG_REF_NAME==mipsfpga_test2_axi_interconnect_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xbar_0 || ORIG_REF_NAME==mipsfpga_test2_xbar_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_axi_gpio_0_0/mipsfpga_test2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_axi_gpio_0_0 || ORIG_REF_NAME==mipsfpga_test2_axi_gpio_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_axi_bram_ctrl_1_0/mipsfpga_test2_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_axi_bram_ctrl_1_0 || ORIG_REF_NAME==mipsfpga_test2_axi_bram_ctrl_1_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_blk_mem_gen_0_1/mipsfpga_test2_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_blk_mem_gen_0_1 || ORIG_REF_NAME==mipsfpga_test2_blk_mem_gen_0_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_axi_uart16550_0_1/mipsfpga_test2_axi_uart16550_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_axi_uart16550_0_1 || ORIG_REF_NAME==mipsfpga_test2_axi_uart16550_0_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xlconcat_0_1/mipsfpga_test2_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xlconcat_0_1 || ORIG_REF_NAME==mipsfpga_test2_xlconcat_0_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_0/mipsfpga_test2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xlconstant_0_0 || ORIG_REF_NAME==mipsfpga_test2_xlconstant_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_1/mipsfpga_test2_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xlconstant_0_1 || ORIG_REF_NAME==mipsfpga_test2_xlconstant_0_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_2/mipsfpga_test2_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xlconstant_0_2 || ORIG_REF_NAME==mipsfpga_test2_xlconstant_0_2}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_clk_wiz_0_0/mipsfpga_test2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_clk_wiz_0_0 || ORIG_REF_NAME==mipsfpga_test2_clk_wiz_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_0_0/mipsfpga_test2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_util_vector_logic_0_0 || ORIG_REF_NAME==mipsfpga_test2_util_vector_logic_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_0_1/mipsfpga_test2_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_util_vector_logic_0_1 || ORIG_REF_NAME==mipsfpga_test2_util_vector_logic_0_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_util_ds_buf_0_0/mipsfpga_test2_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_util_ds_buf_0_0 || ORIG_REF_NAME==mipsfpga_test2_util_ds_buf_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_3/mipsfpga_test2_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_xlconstant_0_3 || ORIG_REF_NAME==mipsfpga_test2_xlconstant_0_3}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_mig_7series_0_0/mipsfpga_test2_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_mig_7series_0_0 || ORIG_REF_NAME==mipsfpga_test2_mig_7series_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_2_0/mipsfpga_test2_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_util_vector_logic_2_0 || ORIG_REF_NAME==mipsfpga_test2_util_vector_logic_2_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_PWM_w_Int_1_0/mipsfpga_test2_PWM_w_Int_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_PWM_w_Int_1_0 || ORIG_REF_NAME==mipsfpga_test2_PWM_w_Int_1_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_axi_tft_0_0/mipsfpga_test2_axi_tft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_axi_tft_0_0 || ORIG_REF_NAME==mipsfpga_test2_axi_tft_0_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_0/mipsfpga_test2_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_ds_0 || ORIG_REF_NAME==mipsfpga_test2_auto_ds_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_0/mipsfpga_test2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_pc_0 || ORIG_REF_NAME==mipsfpga_test2_auto_pc_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_cc_0/mipsfpga_test2_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_cc_0 || ORIG_REF_NAME==mipsfpga_test2_auto_cc_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_1/mipsfpga_test2_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_ds_1 || ORIG_REF_NAME==mipsfpga_test2_auto_ds_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_2/mipsfpga_test2_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_ds_2 || ORIG_REF_NAME==mipsfpga_test2_auto_ds_2}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_1/mipsfpga_test2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_pc_1 || ORIG_REF_NAME==mipsfpga_test2_auto_pc_1}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_3/mipsfpga_test2_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_ds_3 || ORIG_REF_NAME==mipsfpga_test2_auto_ds_3}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_2/mipsfpga_test2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_pc_2 || ORIG_REF_NAME==mipsfpga_test2_auto_pc_2}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_4/mipsfpga_test2_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_ds_4 || ORIG_REF_NAME==mipsfpga_test2_auto_ds_4}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_3/mipsfpga_test2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_pc_3 || ORIG_REF_NAME==mipsfpga_test2_auto_pc_3}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_0/mipsfpga_test2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_us_0 || ORIG_REF_NAME==mipsfpga_test2_auto_us_0}]

# IP: bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_1/mipsfpga_test2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipsfpga_test2_auto_us_1 || ORIG_REF_NAME==mipsfpga_test2_auto_us_1}]

# XDC: bd/mipsfpga_test2/mipsfpga_test2_ooc.xdc
