# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.cache/wt [current_project]
set_property parent.project_path E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Peripheral_Interface_lab/ip_repo [current_project]
add_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/imports/new/ram_init.coe
add_files E:/Peripheral_Interface_lab/ram_init.coe
add_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/imports/Users/project_1/project_1.srcs/sources_1/new/ram_init.coe
add_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/new/ram_init.coe
add_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/mipsfpga_test2.bd
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_MIPS_MicroAptiv_UP_0_0/mipsfpga_test2_MIPS_MicroAptiv_UP_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_ahblite_axi_bridge_0_0/mipsfpga_test2_ahblite_axi_bridge_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_ahblite_axi_bridge_0_0/mipsfpga_test2_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xbar_0/mipsfpga_test2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_gpio_0_0/mipsfpga_test2_axi_gpio_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_gpio_0_0/mipsfpga_test2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_gpio_0_0/mipsfpga_test2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_gpio_0_0/mipsfpga_test2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_bram_ctrl_1_0/mipsfpga_test2_axi_bram_ctrl_1_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_bram_ctrl_1_0/mipsfpga_test2_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_blk_mem_gen_0_1/mipsfpga_test2_blk_mem_gen_0_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_blk_mem_gen_0_1/mipsfpga_test2_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_uart16550_0_1/mipsfpga_test2_axi_uart16550_0_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_uart16550_0_1/mipsfpga_test2_axi_uart16550_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_uart16550_0_1/mipsfpga_test2_axi_uart16550_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_uart16550_0_1/mipsfpga_test2_axi_uart16550_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xlconcat_0_1/mipsfpga_test2_xlconcat_0_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_0/mipsfpga_test2_xlconstant_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_1/mipsfpga_test2_xlconstant_0_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_2/mipsfpga_test2_xlconstant_0_2.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_clk_wiz_0_0/mipsfpga_test2_clk_wiz_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_clk_wiz_0_0/mipsfpga_test2_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_clk_wiz_0_0/mipsfpga_test2_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_clk_wiz_0_0/mipsfpga_test2_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_0_0/mipsfpga_test2_util_vector_logic_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_0_1/mipsfpga_test2_util_vector_logic_0_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_util_ds_buf_0_0/mipsfpga_test2_util_ds_buf_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_xlconstant_0_3/mipsfpga_test2_xlconstant_0_3.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_mig_7series_0_0/mipsfpga_test2_mig_7series_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_mig_7series_0_0/mipsfpga_test2_mig_7series_0_0/user_design/constraints/mipsfpga_test2_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_mig_7series_0_0/mipsfpga_test2_mig_7series_0_0/user_design/constraints/mipsfpga_test2_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_util_vector_logic_2_0/mipsfpga_test2_util_vector_logic_2_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_PWM_w_Int_1_0/mipsfpga_test2_PWM_w_Int_1_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_tft_0_0/mipsfpga_test2_axi_tft_0_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_tft_0_0/mipsfpga_test2_axi_tft_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_tft_0_0/mipsfpga_test2_axi_tft_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_axi_tft_0_0/mipsfpga_test2_axi_tft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_0/mipsfpga_test2_auto_ds_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_0/mipsfpga_test2_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_0/mipsfpga_test2_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_0/mipsfpga_test2_auto_pc_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_0/mipsfpga_test2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_cc_0/mipsfpga_test2_auto_cc_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_cc_0/mipsfpga_test2_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_cc_0/mipsfpga_test2_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_1/mipsfpga_test2_auto_ds_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_1/mipsfpga_test2_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_1/mipsfpga_test2_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_2/mipsfpga_test2_auto_ds_2.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_2/mipsfpga_test2_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_2/mipsfpga_test2_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_1/mipsfpga_test2_auto_pc_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_1/mipsfpga_test2_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_3/mipsfpga_test2_auto_ds_3.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_3/mipsfpga_test2_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_3/mipsfpga_test2_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_2/mipsfpga_test2_auto_pc_2.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_2/mipsfpga_test2_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_4/mipsfpga_test2_auto_ds_4.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_4/mipsfpga_test2_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_ds_4/mipsfpga_test2_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_3/mipsfpga_test2_auto_pc_3.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_pc_3/mipsfpga_test2_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_0/mipsfpga_test2_auto_us_0.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_0/mipsfpga_test2_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_0/mipsfpga_test2_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_1/mipsfpga_test2_auto_us_1.dcp]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_1/mipsfpga_test2_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/ip/mipsfpga_test2_auto_us_1/mipsfpga_test2_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/mipsfpga_test2_ooc.xdc]
set_property is_locked true [get_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/mipsfpga_test2.bd]

read_verilog -library xil_defaultlib E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/sources_1/bd/mipsfpga_test2/hdl/mipsfpga_test2_wrapper.v
read_xdc E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/constrs_1/imports/git/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/Peripheral_Interface_lab/mipsfpga_test2/mipsfpga_test2.srcs/constrs_1/imports/git/Nexys4DDR_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top mipsfpga_test2_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef mipsfpga_test2_wrapper.dcp
catch { report_utilization -file mipsfpga_test2_wrapper_utilization_synth.rpt -pb mipsfpga_test2_wrapper_utilization_synth.pb }
